dataset:
  repo_id: omy_pnp
  root: ./omy_pnp
policy:
  type : pi0
  chunk_size: 5
  n_action_steps: 5
save_checkpoint: true
output_dir: ./ckpt/pi0_omy
batch_size: 16
job_name : pi0_omy
resume: false
seed : 42
num_workers: 8
steps: 20_000
eval_freq: -1 # No evaluation
log_freq: 50
save_checkpoint: true
save_freq: 5_000
use_policy_training_preset: true
  
wandb:
  enable: true
  project: pi0_omy
  entity: YOUR ENTITY
  disable_artifact: true